import { adminWorldMonsterTotal,aisultanMonsterTotal,anuarBombEnemiesTotal,arailmEnemiesTotal,baseDragonHp,bbiMonsterTotal,finalSpiritMonsterTotal,furyDungeonEnemiesTotal,heroMaxHp,mansurDungeonEnemiesTotal,monsterAvalancheTotal,monstersPerCity,nuraliMonsterTotal } from '../data/adminBoss';
import { dragonSons } from '../data/arcaneSpells';
import { heroMaxMana,type GameSaveState } from '../data/gameSaveState';
import type { GameViewModel } from '../useGameController';

type Context = Pick<GameViewModel, 'setChapter' | 'setHealthLevel' | 'setHeroHp' | 'currentHeroMaxHp' | 'setEnemyHp' | 'setMessage' | 'setSavedCities' | 'setVictory' | 'setEndingChoice' | 'setSecretEnding' | 'setGoblinKingReady' | 'setGoblinKingFightStarted' | 'setFuryGateOpen' | 'setFuryDungeonEntered' | 'setFuryMonstersLeft' | 'setFuryChoiceOpen' | 'setFuryKingFightStarted' | 'setAnuarGateOpen' | 'setAnuarWorldEntered' | 'setAnuarBombsLeft' | 'setAnuarKingFightStarted' | 'setMansurGateOpen' | 'setMansurDungeonEntered' | 'setMansurMonstersLeft' | 'setMansurKingFightStarted' | 'setArailmGateOpen' | 'setArailmWorldEntered' | 'setArailmMonstersLeft' | 'setArailmChoiceOpen' | 'setArailmKingFightStarted' | 'setAisGateOpen' | 'setAisWorldEntered' | 'setAisMonstersLeft' | 'setAisSharkFightStarted' | 'setAisFinalChoiceOpen' | 'setAisGodFightStarted' | 'setAdminWorldGateOpen' | 'setAdminWorldEntered' | 'setAdminWorldMonstersLeft' | 'setAdminWorldBossesStarted' | 'setAdminFinalChoiceOpen' | 'setAdminBossFightStarted' | 'setBbiGateOpen' | 'setBbiWorldEntered' | 'setBbiMonstersLeft' | 'setBbiBossStage' | 'setBbiFinalChoiceOpen' | 'setBbiCityReward' | 'setBbiBadEnding' | 'setImpossibleEnding' | 'setNuraliGateOpen' | 'setNuraliWorldEntered' | 'setNuraliMonstersLeft' | 'setNuraliChoiceOpen' | 'setNuraliBossFightStarted' | 'setMonsterAvalancheEntered' | 'setMonsterAvalancheLeft' | 'setMonsterAvalancheEnding' | 'setFinalSpiritWorldOpen' | 'setFinalSpiritMonstersLeft' | 'setFinalSpiritFightStarted' | 'setDeathGodFightStarted' | 'setGold' | 'setGoldMultiplier' | 'setInfiniteGold' | 'setDungeon' | 'setRelics' | 'setWeapons' | 'setEquippedWeapon' | 'setArmors' | 'setEquippedArmor' | 'setEquippedArtifactId' | 'setHeroMana' | 'setHeroPosition' | 'setHeroDirection' | 'setMapLocationIndex' | 'setCityMonsters' | 'setDuelWins' | 'setItems' | 'setShopLevels' | 'setIntroSkipped' | 'paidQuestIds'>;

export function runApplyGameSave(context: Context, save: Partial<GameSaveState>): void {
  const { setChapter, setHealthLevel, setHeroHp, currentHeroMaxHp, setEnemyHp, setMessage, setSavedCities, setVictory, setEndingChoice, setSecretEnding, setGoblinKingReady, setGoblinKingFightStarted, setFuryGateOpen, setFuryDungeonEntered, setFuryMonstersLeft, setFuryChoiceOpen, setFuryKingFightStarted, setAnuarGateOpen, setAnuarWorldEntered, setAnuarBombsLeft, setAnuarKingFightStarted, setMansurGateOpen, setMansurDungeonEntered, setMansurMonstersLeft, setMansurKingFightStarted, setArailmGateOpen, setArailmWorldEntered, setArailmMonstersLeft, setArailmChoiceOpen, setArailmKingFightStarted, setAisGateOpen, setAisWorldEntered, setAisMonstersLeft, setAisSharkFightStarted, setAisFinalChoiceOpen, setAisGodFightStarted, setAdminWorldGateOpen, setAdminWorldEntered, setAdminWorldMonstersLeft, setAdminWorldBossesStarted, setAdminFinalChoiceOpen, setAdminBossFightStarted, setBbiGateOpen, setBbiWorldEntered, setBbiMonstersLeft, setBbiBossStage, setBbiFinalChoiceOpen, setBbiCityReward, setBbiBadEnding, setImpossibleEnding, setNuraliGateOpen, setNuraliWorldEntered, setNuraliMonstersLeft, setNuraliChoiceOpen, setNuraliBossFightStarted, setMonsterAvalancheEntered, setMonsterAvalancheLeft, setMonsterAvalancheEnding, setFinalSpiritWorldOpen, setFinalSpiritMonstersLeft, setFinalSpiritFightStarted, setDeathGodFightStarted, setGold, setGoldMultiplier, setInfiniteGold, setDungeon, setRelics, setWeapons, setEquippedWeapon, setArmors, setEquippedArmor, setEquippedArtifactId, setHeroMana, setHeroPosition, setHeroDirection, setMapLocationIndex, setCityMonsters, setDuelWins, setItems, setShopLevels, setIntroSkipped, paidQuestIds } = context;
    setChapter(save.chapter ?? 0);
    setHealthLevel(save.healthLevel ?? 0);
    setHeroHp(Math.min(save.heroHp ?? heroMaxHp, currentHeroMaxHp));
    setEnemyHp(save.enemyHp ?? baseDragonHp);
    setMessage(save.message ?? 'Сейв загружен из Supabase.');
    setSavedCities(save.savedCities ?? []);
    setVictory(save.victory ?? false);
    setEndingChoice(save.endingChoice ?? null);
    setSecretEnding(save.secretEnding ?? null);
    setGoblinKingReady(save.goblinKingReady ?? false);
    setGoblinKingFightStarted(save.goblinKingFightStarted ?? false);
    setFuryGateOpen(save.furyGateOpen ?? false);
    setFuryDungeonEntered(save.furyDungeonEntered ?? false);
    setFuryMonstersLeft(save.furyMonstersLeft ?? furyDungeonEnemiesTotal);
    setFuryChoiceOpen(save.furyChoiceOpen ?? false);
    setFuryKingFightStarted(save.furyKingFightStarted ?? false);
    setAnuarGateOpen(save.anuarGateOpen ?? false);
    setAnuarWorldEntered(save.anuarWorldEntered ?? false);
    setAnuarBombsLeft(save.anuarBombsLeft ?? anuarBombEnemiesTotal);
    setAnuarKingFightStarted(save.anuarKingFightStarted ?? false);
    setMansurGateOpen(save.mansurGateOpen ?? false);
    setMansurDungeonEntered(save.mansurDungeonEntered ?? false);
    setMansurMonstersLeft(save.mansurMonstersLeft ?? mansurDungeonEnemiesTotal);
    setMansurKingFightStarted(save.mansurKingFightStarted ?? false);
    setArailmGateOpen(save.arailmGateOpen ?? false);
    setArailmWorldEntered(save.arailmWorldEntered ?? false);
    setArailmMonstersLeft(save.arailmMonstersLeft ?? arailmEnemiesTotal);
    setArailmChoiceOpen(save.arailmChoiceOpen ?? false);
    setArailmKingFightStarted(save.arailmKingFightStarted ?? false);
    setAisGateOpen(save.aisGateOpen ?? false);
    setAisWorldEntered(save.aisWorldEntered ?? false);
    setAisMonstersLeft(save.aisMonstersLeft ?? aisultanMonsterTotal);
    setAisSharkFightStarted(save.aisSharkFightStarted ?? false);
    setAisFinalChoiceOpen(save.aisFinalChoiceOpen ?? false);
    setAisGodFightStarted(save.aisGodFightStarted ?? false);
    setAdminWorldGateOpen(save.adminWorldGateOpen ?? false);
    setAdminWorldEntered(save.adminWorldEntered ?? false);
    setAdminWorldMonstersLeft(save.adminWorldMonstersLeft ?? adminWorldMonsterTotal);
    setAdminWorldBossesStarted(save.adminWorldBossesStarted ?? false);
    setAdminFinalChoiceOpen(save.adminFinalChoiceOpen ?? false);
    setAdminBossFightStarted(save.adminBossFightStarted ?? false);
    setBbiGateOpen(save.bbiGateOpen ?? false);
    setBbiWorldEntered(save.bbiWorldEntered ?? false);
    setBbiMonstersLeft(save.bbiMonstersLeft ?? bbiMonsterTotal);
    setBbiBossStage(save.bbiBossStage ?? null);
    setBbiFinalChoiceOpen(save.bbiFinalChoiceOpen ?? false);
    setBbiCityReward(save.bbiCityReward ?? false);
    setBbiBadEnding(save.bbiBadEnding ?? false);
    setImpossibleEnding(save.impossibleEnding ?? false);
    setNuraliGateOpen(save.nuraliGateOpen ?? false);
    setNuraliWorldEntered(save.nuraliWorldEntered ?? false);
    setNuraliMonstersLeft(save.nuraliMonstersLeft ?? nuraliMonsterTotal);
    setNuraliChoiceOpen(save.nuraliChoiceOpen ?? false);
    setNuraliBossFightStarted(save.nuraliBossFightStarted ?? false);
    setMonsterAvalancheEntered(save.monsterAvalancheEntered ?? false);
    setMonsterAvalancheLeft(save.monsterAvalancheLeft ?? monsterAvalancheTotal);
    setMonsterAvalancheEnding(save.monsterAvalancheEnding ?? false);
    setFinalSpiritWorldOpen(save.finalSpiritWorldOpen ?? false);
    setFinalSpiritMonstersLeft(save.finalSpiritMonstersLeft ?? finalSpiritMonsterTotal);
    setFinalSpiritFightStarted(save.finalSpiritFightStarted ?? false);
    setDeathGodFightStarted(save.deathGodFightStarted ?? false);
    setGold(save.gold ?? 0);
    setGoldMultiplier(save.goldMultiplier ?? 1);
    setInfiniteGold(save.infiniteGold ?? false);
    setDungeon(save.dungeon ?? null);
    setRelics(save.relics ?? []);
    setWeapons(save.weapons ?? []);
    setEquippedWeapon(save.equippedWeapon ?? null);
    setArmors(save.armors ?? []);
    setEquippedArmor(save.equippedArmor ?? null);
    setEquippedArtifactId(save.equippedArtifactId ?? null);
    setHeroMana(save.heroMana ?? heroMaxMana);
    setHeroPosition(save.heroPosition ?? { x: -18_000, z: 0 });
    setHeroDirection(save.heroDirection ?? { x: 0, z: -1 });
    setMapLocationIndex(save.mapLocationIndex ?? 0);
    setCityMonsters(save.cityMonsters ?? dragonSons.map(() => monstersPerCity));
    setDuelWins(save.duelWins ?? 0);
    setItems(save.items ?? { sword: 0, pet: 0, clothes: 0, helmet: 0, armor: 0, mana: 0, health: 0, doubleStrike: 0 });
    setShopLevels(save.shopLevels ?? { sword: 0, pet: 0, clothes: 0, helmet: 0, armor: 0, mana: 0, health: 0, doubleStrike: 0 });
    setIntroSkipped(save.introSkipped ?? false);
    paidQuestIds.current = new Set(save.paidQuestIds ?? []);
  
}
