import { browserStorage } from '../../lib/browserStorage';
import { saveWinStreakState } from '../data/getLocalDateKey';
import { adminWorldMonsterTotal,aisultanMonsterTotal,anuarBombEnemiesTotal,arailmEnemiesTotal,baseDragonHp,bbiMonsterTotal,finalSpiritMonsterTotal,furyDungeonEnemiesTotal,heroMaxHp,mansurDungeonEnemiesTotal,monsterAvalancheTotal,monstersPerCity,nuraliMonsterTotal } from '../data/adminBoss';
import { dragonSons } from '../data/arcaneSpells';
import { heroMaxMana } from '../data/gameSaveState';
import type { GameViewModel } from '../useGameController';

type Context = Pick<GameViewModel, 'setChapter' | 'setHealthLevel' | 'setHeroHp' | 'setEnemyHp' | 'setMessage' | 'setSavedCities' | 'setVictory' | 'setEndingChoice' | 'setSecretEnding' | 'setGoblinKingReady' | 'setGoblinKingFightStarted' | 'setFuryGateOpen' | 'setFuryDungeonEntered' | 'setFuryMonstersLeft' | 'setFuryChoiceOpen' | 'setFuryKingFightStarted' | 'setAnuarGateOpen' | 'setAnuarWorldEntered' | 'setAnuarBombsLeft' | 'setAnuarKingFightStarted' | 'setMansurGateOpen' | 'setMansurDungeonEntered' | 'setMansurMonstersLeft' | 'setMansurKingFightStarted' | 'setArailmGateOpen' | 'setArailmWorldEntered' | 'setArailmMonstersLeft' | 'setArailmChoiceOpen' | 'setArailmKingFightStarted' | 'setAisGateOpen' | 'setAisWorldEntered' | 'setAisMonstersLeft' | 'setAisSharkFightStarted' | 'setAisFinalChoiceOpen' | 'setAisGodFightStarted' | 'setAdminWorldGateOpen' | 'setAdminWorldEntered' | 'setAdminWorldMonstersLeft' | 'setAdminWorldBossesStarted' | 'setAdminFinalChoiceOpen' | 'setAdminBossFightStarted' | 'setBbiGateOpen' | 'setBbiWorldEntered' | 'setBbiMonstersLeft' | 'setBbiBossStage' | 'setBbiFinalChoiceOpen' | 'setBbiCityReward' | 'setBbiBadEnding' | 'setImpossibleEnding' | 'setNuraliGateOpen' | 'setNuraliWorldEntered' | 'setNuraliMonstersLeft' | 'setNuraliChoiceOpen' | 'setNuraliBossFightStarted' | 'setMonsterAvalancheEntered' | 'setMonsterAvalancheLeft' | 'setMonsterAvalancheEnding' | 'setFinalSpiritWorldOpen' | 'setFinalSpiritMonstersLeft' | 'setFinalSpiritFightStarted' | 'setDeathGodFightStarted' | 'setGold' | 'setGoldMultiplier' | 'setInfiniteGold' | 'setDungeon' | 'setRelics' | 'setWeapons' | 'setEquippedWeapon' | 'setArmors' | 'setEquippedArmor' | 'setEquippedArtifactId' | 'setHeroMana' | 'setShopTab' | 'setHeroAnimation' | 'setHeroPosition' | 'setHeroHeight' | 'setHeroDirection' | 'setMapLocationIndex' | 'verticalVelocity' | 'setCityMonsters' | 'setMonsterAttackCount' | 'setBattlePulse' | 'setFireWavePulse' | 'setWaterWavePulse' | 'setEnemyBurning' | 'setDuelStatus' | 'setDuelOpponent' | 'setDuelWins' | 'setDuelHeroHp' | 'setDuelOpponentHp' | 'setDuelTradeOpen' | 'setDuelChatMessages' | 'setDuelChatText' | 'paidQuestIds' | 'setItems' | 'setShopLevels' | 'setIntroSkipped' | 'setWinStreakState' | 'setWinStreakText'>;

export function runRestart(context: Context, storageKey: string): void {
  const { setChapter, setHealthLevel, setHeroHp, setEnemyHp, setMessage, setSavedCities, setVictory, setEndingChoice, setSecretEnding, setGoblinKingReady, setGoblinKingFightStarted, setFuryGateOpen, setFuryDungeonEntered, setFuryMonstersLeft, setFuryChoiceOpen, setFuryKingFightStarted, setAnuarGateOpen, setAnuarWorldEntered, setAnuarBombsLeft, setAnuarKingFightStarted, setMansurGateOpen, setMansurDungeonEntered, setMansurMonstersLeft, setMansurKingFightStarted, setArailmGateOpen, setArailmWorldEntered, setArailmMonstersLeft, setArailmChoiceOpen, setArailmKingFightStarted, setAisGateOpen, setAisWorldEntered, setAisMonstersLeft, setAisSharkFightStarted, setAisFinalChoiceOpen, setAisGodFightStarted, setAdminWorldGateOpen, setAdminWorldEntered, setAdminWorldMonstersLeft, setAdminWorldBossesStarted, setAdminFinalChoiceOpen, setAdminBossFightStarted, setBbiGateOpen, setBbiWorldEntered, setBbiMonstersLeft, setBbiBossStage, setBbiFinalChoiceOpen, setBbiCityReward, setBbiBadEnding, setImpossibleEnding, setNuraliGateOpen, setNuraliWorldEntered, setNuraliMonstersLeft, setNuraliChoiceOpen, setNuraliBossFightStarted, setMonsterAvalancheEntered, setMonsterAvalancheLeft, setMonsterAvalancheEnding, setFinalSpiritWorldOpen, setFinalSpiritMonstersLeft, setFinalSpiritFightStarted, setDeathGodFightStarted, setGold, setGoldMultiplier, setInfiniteGold, setDungeon, setRelics, setWeapons, setEquippedWeapon, setArmors, setEquippedArmor, setEquippedArtifactId, setHeroMana, setShopTab, setHeroAnimation, setHeroPosition, setHeroHeight, setHeroDirection, setMapLocationIndex, verticalVelocity, setCityMonsters, setMonsterAttackCount, setBattlePulse, setFireWavePulse, setWaterWavePulse, setEnemyBurning, setDuelStatus, setDuelOpponent, setDuelWins, setDuelHeroHp, setDuelOpponentHp, setDuelTradeOpen, setDuelChatMessages, setDuelChatText, paidQuestIds, setItems, setShopLevels, setIntroSkipped, setWinStreakState, setWinStreakText } = context;
    browserStorage.removeItem(storageKey);
    setChapter(0);
    setHealthLevel(0);
    setHeroHp(heroMaxHp);
    setEnemyHp(baseDragonHp);
    setMessage('Мир снова в огне. Начинается новый поход за спасение городов.');
    setSavedCities([]);
    setVictory(false);
    setEndingChoice(null);
    setSecretEnding(null);
    setGoblinKingReady(false);
    setGoblinKingFightStarted(false);
    setFuryGateOpen(false);
    setFuryDungeonEntered(false);
    setFuryMonstersLeft(furyDungeonEnemiesTotal);
    setFuryChoiceOpen(false);
    setFuryKingFightStarted(false);
    setAnuarGateOpen(false);
    setAnuarWorldEntered(false);
    setAnuarBombsLeft(anuarBombEnemiesTotal);
    setAnuarKingFightStarted(false);
    setMansurGateOpen(false);
    setMansurDungeonEntered(false);
    setMansurMonstersLeft(mansurDungeonEnemiesTotal);
    setMansurKingFightStarted(false);
    setArailmGateOpen(false);
    setArailmWorldEntered(false);
    setArailmMonstersLeft(arailmEnemiesTotal);
    setArailmChoiceOpen(false);
    setArailmKingFightStarted(false);
    setAisGateOpen(false);
    setAisWorldEntered(false);
    setAisMonstersLeft(aisultanMonsterTotal);
    setAisSharkFightStarted(false);
    setAisFinalChoiceOpen(false);
    setAisGodFightStarted(false);
    setAdminWorldGateOpen(false);
    setAdminWorldEntered(false);
    setAdminWorldMonstersLeft(adminWorldMonsterTotal);
    setAdminWorldBossesStarted(false);
    setAdminFinalChoiceOpen(false);
    setAdminBossFightStarted(false);
    setBbiGateOpen(false);
    setBbiWorldEntered(false);
    setBbiMonstersLeft(bbiMonsterTotal);
    setBbiBossStage(null);
    setBbiFinalChoiceOpen(false);
    setBbiCityReward(false);
    setBbiBadEnding(false);
    setImpossibleEnding(false);
    setNuraliGateOpen(false);
    setNuraliWorldEntered(false);
    setNuraliMonstersLeft(nuraliMonsterTotal);
    setNuraliChoiceOpen(false);
    setNuraliBossFightStarted(false);
    setMonsterAvalancheEntered(false);
    setMonsterAvalancheLeft(monsterAvalancheTotal);
    setMonsterAvalancheEnding(false);
    setFinalSpiritWorldOpen(false);
    setFinalSpiritMonstersLeft(finalSpiritMonsterTotal);
    setFinalSpiritFightStarted(false);
    setDeathGodFightStarted(false);
    setGold(0);
    setGoldMultiplier(1);
    setInfiniteGold(false);
    setDungeon(null);
    setRelics([]);
    setWeapons([]);
    setEquippedWeapon(null);
    setEquippedArtifactId(null);
    setArmors([]);
    setEquippedArmor(null);
    setShopTab('upgrades');
    setHeroMana(heroMaxMana);
    setHeroAnimation('idle');
    setHeroPosition({ x: -18_000, z: 0 });
    setHeroHeight(0);
    setHeroDirection({ x: 0, z: -1 });
    setMapLocationIndex(0);
    verticalVelocity.current = 0;
    setCityMonsters(dragonSons.map(() => monstersPerCity));
    setMonsterAttackCount(0);
    setBattlePulse(0);
    setFireWavePulse(0);
    setWaterWavePulse(0);
    setEnemyBurning(false);
    setDuelStatus('idle');
    setDuelOpponent(null);
    setDuelWins(0);
    setDuelHeroHp(0);
    setDuelOpponentHp(0);
    setDuelTradeOpen(false);
    setDuelChatMessages([]);
    setDuelChatText('');
    paidQuestIds.current.clear();
    const resetWinStreak = { current: 0, best: 0, totalWins: 0 };
    setWinStreakState(resetWinStreak);
    saveWinStreakState(resetWinStreak);
    setWinStreakText('Винстрик сброшен.');
    setIntroSkipped(false);
    setItems({ sword: 0, pet: 0, clothes: 0, helmet: 0, armor: 0, mana: 0, health: 0, doubleStrike: 0 });
    setShopLevels({ sword: 0, pet: 0, clothes: 0, helmet: 0, armor: 0, mana: 0, health: 0, doubleStrike: 0 });
  
}
