import { browserStorage } from '../../lib/browserStorage';
import { adminWorldMonsterTotal,aisultanMonsterTotal,anuarBombEnemiesTotal,arailmEnemiesTotal,baseDragonHp,bbiMonsterTotal,finalSpiritMonsterTotal,furyDungeonEnemiesTotal,heroMaxHp,mansurDungeonEnemiesTotal,monsterAvalancheStartChapter,monsterAvalancheTotal,monstersPerCity,nuraliMonsterTotal } from '../data/adminBoss';
import { dragonSons } from '../data/arcaneSpells';
import { gameSaveStorageKey } from '../data/gameSaveState';
import { scaledDragonPower } from '../data/isDeathSword';
import type { GameViewModel } from '../useGameController';

type Context = Pick<GameViewModel, 'unlockedAchievements' | 'setChapter' | 'setHealthLevel' | 'setHeroHp' | 'setEnemyHp' | 'setMessage' | 'setSavedCities' | 'setVictory' | 'setEndingChoice' | 'setSecretEnding' | 'setGoblinKingReady' | 'setGoblinKingFightStarted' | 'setFuryGateOpen' | 'setFuryDungeonEntered' | 'setFuryMonstersLeft' | 'setFuryChoiceOpen' | 'setFuryKingFightStarted' | 'setAnuarGateOpen' | 'setAnuarWorldEntered' | 'setAnuarBombsLeft' | 'setAnuarKingFightStarted' | 'setMansurGateOpen' | 'setMansurDungeonEntered' | 'setMansurMonstersLeft' | 'setMansurKingFightStarted' | 'setArailmGateOpen' | 'setArailmWorldEntered' | 'setArailmMonstersLeft' | 'setArailmChoiceOpen' | 'setArailmKingFightStarted' | 'setAisGateOpen' | 'setAisWorldEntered' | 'setAisMonstersLeft' | 'setAisSharkFightStarted' | 'setAisFinalChoiceOpen' | 'setAisGodFightStarted' | 'setAdminWorldGateOpen' | 'setAdminWorldEntered' | 'setAdminWorldMonstersLeft' | 'setAdminWorldBossesStarted' | 'setAdminFinalChoiceOpen' | 'setAdminBossFightStarted' | 'setBbiGateOpen' | 'setBbiWorldEntered' | 'setBbiMonstersLeft' | 'setBbiBossStage' | 'setBbiFinalChoiceOpen' | 'setBbiCityReward' | 'setBbiBadEnding' | 'setNuraliGateOpen' | 'setNuraliWorldEntered' | 'setNuraliMonstersLeft' | 'setNuraliChoiceOpen' | 'setNuraliBossFightStarted' | 'setMonsterAvalancheEntered' | 'setMonsterAvalancheLeft' | 'setMonsterAvalancheEnding' | 'setFinalSpiritWorldOpen' | 'setFinalSpiritMonstersLeft' | 'setFinalSpiritFightStarted' | 'setGold' | 'setGoldMultiplier' | 'setInfiniteGold' | 'setDungeon' | 'setRelics' | 'setWeapons' | 'setEquippedWeapon' | 'setArmors' | 'setEquippedArmor' | 'setShopTab' | 'setHeroAnimation' | 'setHeroPosition' | 'setHeroHeight' | 'verticalVelocity' | 'setCityMonsters' | 'setMonsterAttackCount' | 'setBattlePulse' | 'setFireWavePulse' | 'setWaterWavePulse' | 'setEnemyBurning' | 'setDuelStatus' | 'setDuelOpponent' | 'setDuelWins' | 'setDuelHeroHp' | 'setDuelOpponentHp' | 'setDuelTradeOpen' | 'setDuelChatMessages' | 'setDuelChatText' | 'paidQuestIds' | 'setItems' | 'setShopLevels'>;

export function runRestart(context: Context): void {
  const { unlockedAchievements, setChapter, setHealthLevel, setHeroHp, setEnemyHp, setMessage, setSavedCities, setVictory, setEndingChoice, setSecretEnding, setGoblinKingReady, setGoblinKingFightStarted, setFuryGateOpen, setFuryDungeonEntered, setFuryMonstersLeft, setFuryChoiceOpen, setFuryKingFightStarted, setAnuarGateOpen, setAnuarWorldEntered, setAnuarBombsLeft, setAnuarKingFightStarted, setMansurGateOpen, setMansurDungeonEntered, setMansurMonstersLeft, setMansurKingFightStarted, setArailmGateOpen, setArailmWorldEntered, setArailmMonstersLeft, setArailmChoiceOpen, setArailmKingFightStarted, setAisGateOpen, setAisWorldEntered, setAisMonstersLeft, setAisSharkFightStarted, setAisFinalChoiceOpen, setAisGodFightStarted, setAdminWorldGateOpen, setAdminWorldEntered, setAdminWorldMonstersLeft, setAdminWorldBossesStarted, setAdminFinalChoiceOpen, setAdminBossFightStarted, setBbiGateOpen, setBbiWorldEntered, setBbiMonstersLeft, setBbiBossStage, setBbiFinalChoiceOpen, setBbiCityReward, setBbiBadEnding, setNuraliGateOpen, setNuraliWorldEntered, setNuraliMonstersLeft, setNuraliChoiceOpen, setNuraliBossFightStarted, setMonsterAvalancheEntered, setMonsterAvalancheLeft, setMonsterAvalancheEnding, setFinalSpiritWorldOpen, setFinalSpiritMonstersLeft, setFinalSpiritFightStarted, setGold, setGoldMultiplier, setInfiniteGold, setDungeon, setRelics, setWeapons, setEquippedWeapon, setArmors, setEquippedArmor, setShopTab, setHeroAnimation, setHeroPosition, setHeroHeight, verticalVelocity, setCityMonsters, setMonsterAttackCount, setBattlePulse, setFireWavePulse, setWaterWavePulse, setEnemyBurning, setDuelStatus, setDuelOpponent, setDuelWins, setDuelHeroHp, setDuelOpponentHp, setDuelTradeOpen, setDuelChatMessages, setDuelChatText, paidQuestIds, setItems, setShopLevels } = context;
    browserStorage.removeItem(gameSaveStorageKey);
    const avalancheCompleted = unlockedAchievements.includes('monsterAvalanche');
    setChapter(avalancheCompleted ? monsterAvalancheStartChapter : 0);
    setHealthLevel(0);
    setHeroHp(heroMaxHp);
    setEnemyHp(avalancheCompleted ? scaledDragonPower(baseDragonHp, monsterAvalancheStartChapter) : baseDragonHp);
    setMessage(avalancheCompleted ? 'После концовки лавины новый поход начинается сразу с 8-го города.' : 'Мир снова в огне. Начинается новый поход за спасение городов.');
    setSavedCities(avalancheCompleted ? dragonSons.slice(0, monsterAvalancheStartChapter).map((city) => `${city.city}, ${city.country}`) : []);
    setVictory(false);
    setEndingChoice(null);
    setSecretEnding(null);
    setGoblinKingReady(false);
    setGoblinKingFightStarted(false);
    setFuryGateOpen(false);
    setFuryDungeonEntered(false);
    setFuryMonstersLeft(furyDungeonEnemiesTotal);
    setFuryChoiceOpen(false);
    setFuryKingFightStarted(false);
    setAnuarGateOpen(false);
    setAnuarWorldEntered(false);
    setAnuarBombsLeft(anuarBombEnemiesTotal);
    setAnuarKingFightStarted(false);
    setMansurGateOpen(false);
    setMansurDungeonEntered(false);
    setMansurMonstersLeft(mansurDungeonEnemiesTotal);
    setMansurKingFightStarted(false);
    setArailmGateOpen(false);
    setArailmWorldEntered(false);
    setArailmMonstersLeft(arailmEnemiesTotal);
    setArailmChoiceOpen(false);
    setArailmKingFightStarted(false);
    setAisGateOpen(false);
    setAisWorldEntered(false);
    setAisMonstersLeft(aisultanMonsterTotal);
    setAisSharkFightStarted(false);
    setAisFinalChoiceOpen(false);
    setAisGodFightStarted(false);
    setAdminWorldGateOpen(false);
    setAdminWorldEntered(false);
    setAdminWorldMonstersLeft(adminWorldMonsterTotal);
    setAdminWorldBossesStarted(false);
    setAdminFinalChoiceOpen(false);
    setAdminBossFightStarted(false);
    setBbiGateOpen(false);
    setBbiWorldEntered(false);
    setBbiMonstersLeft(bbiMonsterTotal);
    setBbiBossStage(null);
    setBbiFinalChoiceOpen(false);
    setBbiCityReward(false);
    setBbiBadEnding(false);
    setNuraliGateOpen(false);
    setNuraliWorldEntered(false);
    setNuraliMonstersLeft(nuraliMonsterTotal);
    setNuraliChoiceOpen(false);
    setNuraliBossFightStarted(false);
    setMonsterAvalancheEntered(false);
    setMonsterAvalancheLeft(monsterAvalancheTotal);
    setMonsterAvalancheEnding(false);
    setFinalSpiritWorldOpen(false);
    setFinalSpiritMonstersLeft(finalSpiritMonsterTotal);
    setFinalSpiritFightStarted(false);
    setGold(0);
    setGoldMultiplier(1);
    setInfiniteGold(false);
    setDungeon(null);
    setRelics([]);
    setWeapons([]);
    setEquippedWeapon(null);
    setArmors([]);
    setEquippedArmor(null);
    setShopTab('upgrades');
    setHeroAnimation('idle');
    setHeroPosition({ x: -18_000, z: 0 });
    setHeroHeight(0);
    verticalVelocity.current = 0;
    setCityMonsters(dragonSons.map((_, index) => avalancheCompleted && index < monsterAvalancheStartChapter ? 0 : monstersPerCity));
    setMonsterAttackCount(0);
    setBattlePulse(0);
    setFireWavePulse(0);
    setWaterWavePulse(0);
    setEnemyBurning(false);
    setDuelStatus('idle');
    setDuelOpponent(null);
    setDuelWins(0);
    setDuelHeroHp(0);
    setDuelOpponentHp(0);
    setDuelTradeOpen(false);
    setDuelChatMessages([]);
    setDuelChatText('');
    paidQuestIds.current.clear();
    setItems({ sword: 0, pet: 0, clothes: 0, helmet: 0, armor: 0, mana: 0, health: 0, doubleStrike: 0 });
    setShopLevels({ sword: 0, pet: 0, clothes: 0, helmet: 0, armor: 0, mana: 0, health: 0, doubleStrike: 0 });
  
}
